name: Backend code format checks

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run black formatter
        uses: psf/black@stable
