name: Frontend code format checks

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,md}
